### ISSUE TITLE
Bug regarding selected bank

### ISSUE THREAD

**Issue by eturnhout** [paynl/shopware-plugin#48]
Hi there,

We use this plugin for one of our webshops and have some issues when updating from 3.2.1 to 3.3.0. After updating I get this error when trying to login as a customer. It's pretty clear what the issue is. It has to do with the newly implemented feature regarding the bank select.

Fatal error: Uncaught TypeError: Argument 1 passed to PaynlPayment\Subscriber\PaymentMethodIssuers::getSelectedBankData() must be of the type integer, null given, called in /var/www/html/custom/plugins/PaynlPayment/Subscriber/PaymentMethodIssuers.php on line 102 and defined in /var/www/html/custom/plugins/PaynlPayment/Subscriber/PaymentMethodIssuers.php:243 Stack trace: #0 /var/www/html/custom/plugins/PaynlPayment/Subscriber/PaymentMethodIssuers.php(102): PaynlPayment\Subscriber\PaymentMethodIssuers->getSelectedBankData(NULL) #1 /var/www/html/vendor/shopware/shopware/engine/Library/Enlight/Event/Handler/Default.php(87): PaynlPayment\Subscriber\PaymentMethodIssuers->onPostDispatchAccount(Object(Enlight_Controller_ActionEventArgs)) #2 /var/www/html/vendor/shopware/shopware/engine/Library/Enlight/Event/EventManager.php(214): Enlight_Event_Handler_Default->execute(Object(Enlight_Controller_ActionEventArgs)) #3 /var/www/html/vendor/shopware/shopware/engine/Library/Enlight/Controller/Action.php(224): Enlight_Event_EventManager- in /var/www/html/custom/plugins/PaynlPayment/Subscriber/PaymentMethodIssuers.php on line 243

Did I miss a note regarding upgrading? We want to update because we are getting lots of exchange request errors and saw there was a fix described in the notes for release 3.3.0

**Comment by woutse** [comment]
Thank you for your message! This issue is solved in the next version, 3.3.1, which will be released very soon. As soon as it's live, i'll leave you a message.

**Comment by eturnhout** [comment]
Thanks! Much appreciated :)

**Comment by woutse** [comment]
The new release is available: https://github.com/paynl/shopware5-plugin/releases/tag/v3.3.1

**Comment by eturnhout** [comment]
Thank! I'll have a look at it.
